name: totalpass
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_easyloading: ^3.0.3
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.1.1
  pull_to_refresh: ^2.0.0
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.0.3
  google_fonts: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.9.2"

flutter_native_splash:
  android: true
  ios: true
  web: true
  color: "#000000"
  image: lib/assets/logo/logo.png
  android_gravity: center
  ios_content_mode: center

flutter:
  uses-material-design: true
  assets:
  - lib/assets/
  - lib/assets/icons/
  - lib/assets/logo/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: 'lib/assets/logo/appLogo.png'
