// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmnyDEg_Bc9ArFaSOx3Gei_GsCbxmA3rg',
    appId: '1:95384856129:web:914a5a18b4f599baf988c0',
    messagingSenderId: '95384856129',
    projectId: 'totalpass-1317b',
    authDomain: 'totalpass-1317b.firebaseapp.com',
    storageBucket: 'totalpass-1317b.appspot.com',
    measurementId: 'G-93JZ3Y9SZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb0bXpXMS1whH10RdW6-6hN91QY0Eu7EA',
    appId: '1:95384856129:android:cd5ff4c28770d853f988c0',
    messagingSenderId: '95384856129',
    projectId: 'totalpass-1317b',
    storageBucket: 'totalpass-1317b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD56t-B36zjlY0pF5topa9NDPG6RPOtyw',
    appId: '1:95384856129:ios:fdbe07c914b4ddcdf988c0',
    messagingSenderId: '95384856129',
    projectId: 'totalpass-1317b',
    storageBucket: 'totalpass-1317b.appspot.com',
    iosClientId: '95384856129-057m2astnp11o74rlcf3a1vhukjn3m5i.apps.googleusercontent.com',
    iosBundleId: 'com.example.totalpass',
  );
}
